name: Deploy to Rancher Desktop
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > ~/.kube/config

      - name: Deploy to K3s Cluster
        run: |
          kubectl rollout restart deployment/my-app -n default --insecure-skip-tls-verify
